/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smk_supermarché;

import java.awt.Menu;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mengi
 */
public class Admin_create_personnel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_create_personnel.class.getName());

    /**
     * Creates new form Admin_create_personnel
     */
    public Admin_create_personnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Btnretour = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        numat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtpost = new javax.swing.JTextField();
        txtprn = new javax.swing.JTextField();
        Dtembauche = new com.toedter.calendar.JDateChooser();
        Dtnaiss = new com.toedter.calendar.JDateChooser();
        role = new javax.swing.JComboBox<>();
        mpass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BtnEnreg = new javax.swing.JButton();
        voir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtmention = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpersonnel = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/SMK_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Super Marché du Kinois ");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATION EMPLOYE");

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Quitter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Btnretour.setBackground(new java.awt.Color(102, 0, 204));
        Btnretour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btnretour.setForeground(new java.awt.Color(255, 255, 255));
        Btnretour.setText("Rétour");
        Btnretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnretourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btnretour, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btnretour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(179, 177, 177), null, new java.awt.Color(204, 204, 204)));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/profil.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("IDENTIFICATION");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Numero Matricul:");

        numat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numatActionPerformed(evt);
            }
        });
        numat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numatKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numatKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nom:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Post-Nom:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Prenom:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Date d'embauche: ");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Date de naissance:");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Rôle:");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Mot de passe:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });

        txtpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpostActionPerformed(evt);
            }
        });
        txtpost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpostKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpostKeyTyped(evt);
            }
        });

        txtprn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprnKeyTyped(evt);
            }
        });

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir", "CAISSIER", "Logisticien" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        mpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpassActionPerformed(evt);
            }
        });
        mpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mpassKeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modifier");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Supprimer");

        BtnEnreg.setBackground(new java.awt.Color(102, 0, 204));
        BtnEnreg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnEnreg.setForeground(new java.awt.Color(255, 255, 255));
        BtnEnreg.setText("Enregistrer");
        BtnEnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnregActionPerformed(evt);
            }
        });
        BtnEnreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEnregKeyPressed(evt);
            }
        });

        voir.setBackground(new java.awt.Color(102, 0, 204));
        voir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        voir.setForeground(new java.awt.Color(255, 255, 255));
        voir.setText("Voir");
        voir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Mention:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtmention.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmentionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(voir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtprn)
                    .addComponent(Dtembauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dtnaiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(role, 0, 191, Short.MAX_VALUE)
                    .addComponent(mpass)
                    .addComponent(txtnom)
                    .addComponent(txtpost)
                    .addComponent(numat)
                    .addComponent(txtmention))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEnreg, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(BtnEnreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(numat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtprn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))
                                    .addComponent(Dtembauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addComponent(Dtnaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(mpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel14)
                    .addComponent(txtmention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbpersonnel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricul", "Nom", "Post-Nom", "Prenom", "Date embauche", "Date de naissance", "Rôle", "Mot de passe"
            }
        ));
        jScrollPane1.setViewportView(tbpersonnel);

        jPanel6.setBackground(new java.awt.Color(102, 0, 204));

        jTextField5.setBackground(new java.awt.Color(102, 0, 204));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Ceci represente l'interface de Création utilisateur, veuillez remplir les informations vous concernant");
        jTextField5.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpassActionPerformed

    private void txtpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpostActionPerformed

    private void numatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numatKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(numat.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zone vide non autorisée");
            }
            else{
                txtnom.requestFocus();
            }
        }
    }//GEN-LAST:event_numatKeyPressed

    private void numatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numatActionPerformed

    private void numatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numatKeyTyped
        // TODO add your handling code here:
       
         if(numat.getText().length()==8){
                evt.consume();
                JOptionPane.showMessageDialog(this,"Seuls 8 caractères sont autorisées");
            }
        
        
    }//GEN-LAST:event_numatKeyTyped

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            if(txtnom.getText().length()==25){
                JOptionPane.showMessageDialog(this,"Seuls 8 caractères sont autorisées");
            }
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtnom.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                txtpost.requestFocus();
            }
        }
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtpostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpostKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            if(txtpost.getText().length()==25){
                JOptionPane.showMessageDialog(this,"Seuls 8 caractères sont autorisées");
            }
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_txtpostKeyTyped

    private void txtpostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpostKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtpost.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                txtprn.requestFocus();
            }
        }
    }//GEN-LAST:event_txtpostKeyPressed

    private void txtprnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtprn.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                Dtembauche.requestFocus();
            }
        }
    }//GEN-LAST:event_txtprnKeyPressed

    private void txtprnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprnKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            if(txtprn.getText().length()==25){
                JOptionPane.showMessageDialog(this,"Seuls 8 caractères sont autorisées");
            }
        }
        else{
            evt.consume();
        }
    }//GEN-LAST:event_txtprnKeyTyped

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
        mpass.requestFocus();
    }//GEN-LAST:event_roleActionPerformed

    private void BtnretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnretourActionPerformed
        // TODO add your handling code here:
        menu Menu=new menu("RH");
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnretourActionPerformed

    private void voirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirActionPerformed
        // TODO add your handling code here:
        char c=mpass.getEchoChar();
        if(c==0){
            mpass.setEchoChar('*');
            voir.setText("Voir");
        }
        else{
              mpass.setEchoChar((char)0);
              voir.setText("Cacher");
        }
    }//GEN-LAST:event_voirActionPerformed

    private void BtnEnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnregActionPerformed
        // TODO add your handling code here:
        if(numat.getText().isEmpty()||txtnom.getText().isEmpty()||txtpost.getText().isEmpty()||txtprn.getText().isEmpty()||Dtembauche.getDate()==null||Dtnaiss.getDate()==null||role.getSelectedIndex()==0||mpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
        }
        else{
            try {
                String numatr=numat.getText();
                String nom_personnel=txtnom.getText();
                String postnom=txtpost.getText();
                String prenom=txtprn.getText();
                String date_embauche=Dtembauche.getDate().toString();
                String datenais=Dtnaiss.getDate().toString();
                String role_utilisateur=role.getSelectedItem().toString();
                String mpass_personnel=mpass.getText();
                String mention=txtmention.getText();
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                Statement enreg=conx.createStatement();
                Boolean L2=enreg.execute("insert into personnels(Matr,Nom,Postnom,Prenom,DateEmbauche,Datenais,Rôle,Mpass,Mention) values"+"('"+numatr+"','"+nom_personnel+"','"+postnom+"','"+prenom+"','"+date_embauche+"','"+datenais+"','"+role_utilisateur+"','"+mpass_personnel+"','"+mention+"')");
                if (!L2){
                    JOptionPane.showMessageDialog(this, "Ligne Ajoutée Avec succès");
                    DefaultTableModel tblpersonnel=(DefaultTableModel)tbpersonnel.getModel();
                    tblpersonnel.addRow(new Object[]{numatr,nom_personnel,postnom,date_embauche,datenais,role_utilisateur,mpass_personnel});
                    numat.setText("");
                    txtnom.setText("");
                    txtpost.setText("");
                    txtprn.setText("");
                    Dtembauche.setDate(null);
                    Dtnaiss.setDate(null);
                    role.setSelectedIndex(0);
                    mpass.setText("");
                    txtmention.setText("");
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
        
    }//GEN-LAST:event_BtnEnregActionPerformed

    private void mpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mpassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(mpass.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"vides non autorisés");
            }
            else{
                txtmention.requestFocus();
            }
        }
    }//GEN-LAST:event_mpassKeyPressed

    private void txtmentionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmentionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtmention.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Zone vides non autorisées ");
            }
            else{
                BtnEnreg.requestFocus();
            }
        }
    }//GEN-LAST:event_txtmentionKeyPressed

    private void BtnEnregKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEnregKeyPressed
        // TODO add your handling code here:
        if(numat.getText().isEmpty()||txtnom.getText().isEmpty()||txtpost.getText().isEmpty()||txtprn.getText().isEmpty()||Dtembauche.getDate()==null||Dtnaiss.getDate()==null||role.getSelectedIndex()==0||mpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
        }
        else{
            try {
                String numatr=numat.getText();
                String nom_personnel=txtnom.getText();
                String postnom=txtpost.getText();
                String prenom=txtprn.getText();
                String date_embauche=Dtembauche.getDate().toString();
                String datenais=Dtnaiss.getDate().toString();
                String role_utilisateur=role.getSelectedItem().toString();
                String mpass_personnel=mpass.getText();
                String mention=txtmention.getText();
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                Statement enreg=conx.createStatement();
                Boolean L2=enreg.execute("insert into personnels(Matr,Nom,Postnom,Prenom,DateEmbauche,Datenais,Rôle,Mpass,Mention) values"+"('"+numatr+"','"+nom_personnel+"','"+postnom+"','"+prenom+"','"+date_embauche+"','"+datenais+"','"+role_utilisateur+"','"+mpass_personnel+"','"+mention+"')");
                if (!L2){
                    JOptionPane.showMessageDialog(this, "Ligne Ajoutée Avec succès");
                    DefaultTableModel tblpersonnel=(DefaultTableModel)tbpersonnel.getModel();
                    tblpersonnel.addRow(new Object[]{numatr,nom_personnel,postnom,date_embauche,datenais,role_utilisateur,mpass_personnel});
                    numat.setText("");
                    txtnom.setText("");
                    txtpost.setText("");
                    txtprn.setText("");
                    Dtembauche.setDate(null);
                    Dtnaiss.setDate(null);
                    role.setSelectedIndex(0);
                    mpass.setText("");
                    txtmention.setText("");
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_BtnEnregKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_create_personnel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnreg;
    private javax.swing.JButton Btnretour;
    private com.toedter.calendar.JDateChooser Dtembauche;
    private com.toedter.calendar.JDateChooser Dtnaiss;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPasswordField mpass;
    private javax.swing.JTextField numat;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTable tbpersonnel;
    private javax.swing.JTextField txtmention;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtprn;
    private javax.swing.JButton voir;
    // End of variables declaration//GEN-END:variables
}
