/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smk_supermarché;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mengi
 */
public class CAISSIER extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CAISSIER.class.getName());
    private String role;

    /**
     * Creates new form CAISSIER
     */
    public CAISSIER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnval = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        btnret = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtpost = new javax.swing.JTextField();
        txtprn = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        quantite = new javax.swing.JTextField();
        combogenr = new javax.swing.JComboBox<>();
        txtcdprod = new javax.swing.JComboBox<>();
        cdfiss = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code marchandise", "Nom ", "Postnom", "Prenom", "Genre", "Tel", "Quantite", "Code fournisseur", "Fidelite"
            }
        ));
        jScrollPane2.setViewportView(tb);

        jPanel5.setBackground(new java.awt.Color(102, 0, 204));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(102, 0, 204));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Ceci represente l'interface Ajout marchandises, veuillez Selectionner votre interface");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnval.setBackground(new java.awt.Color(102, 0, 204));
        btnval.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnval.setForeground(new java.awt.Color(255, 255, 255));
        btnval.setText("VALIDER");
        btnval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalActionPerformed(evt);
            }
        });
        btnval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnvalKeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFIER");

        btnsuppr.setBackground(new java.awt.Color(255, 0, 0));
        btnsuppr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsuppr.setForeground(new java.awt.Color(255, 255, 255));
        btnsuppr.setText("SUPPR");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });

        btnret.setBackground(new java.awt.Color(102, 0, 204));
        btnret.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnret.setForeground(new java.awt.Color(255, 255, 255));
        btnret.setText("RETOUR");
        btnret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nom:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Post-nom:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Prenom:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Genre:");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tel:");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Code produits:");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Quantité:");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Code fournisseur:");

        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
        });

        txtpost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpostKeyPressed(evt);
            }
        });

        txtprn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprnActionPerformed(evt);
            }
        });
        txtprn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprnKeyPressed(evt);
            }
        });

        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelKeyTyped(evt);
            }
        });

        quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantiteActionPerformed(evt);
            }
        });
        quantite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantiteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantiteKeyTyped(evt);
            }
        });

        combogenr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genre", "M", "F" }));
        combogenr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenrActionPerformed(evt);
            }
        });

        txtcdprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir", "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtcdprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcdprodActionPerformed(evt);
            }
        });

        cdfiss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir", "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnval, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnret, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quantite)
                                            .addComponent(txtcdprod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cdfiss, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtpost)
                                            .addComponent(txtprn))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txttel)
                                    .addComponent(combogenr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnret)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtprn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(combogenr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtcdprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cdfiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnval, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/marchandise.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Caissier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5jTextField2ActionPerformed

    private void btnretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretActionPerformed
        // TODO add your handling code here:
        menu Menu= new menu("CAISSIER");
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnretActionPerformed

    private void txtprnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprnActionPerformed

    private void quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteActionPerformed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtnom.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zone vides non autorisées");
            }
            else{
                txtpost.requestFocus();
            }
        }
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtpostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpostKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtpost.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                txtprn.requestFocus();
            }
        }
    }//GEN-LAST:event_txtpostKeyPressed

    private void txtprnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtprn.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                combogenr.requestFocus();
            }
        }
        
    }//GEN-LAST:event_txtprnKeyPressed

    private void combogenrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenrActionPerformed
        // TODO add your handling code here:
        if(combogenr.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Veuillez choisir le genre");
        }
        else{
            txttel.requestFocus();
        }
    }//GEN-LAST:event_combogenrActionPerformed

    private void quantiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantiteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(quantite.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zone vides non autorisées");
            }
            else{
                cdfiss.requestFocus();
            }
        }
    }//GEN-LAST:event_quantiteKeyPressed

    private void txttelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txttel.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zone vides non autorisées");
            }
            else if(txttel.getText().length()<9){
                JOptionPane.showMessageDialog(this,"Vous devriez avoir neufs caractères");
            }
            else{
                txtcdprod.requestFocus();
            }
        }
    }//GEN-LAST:event_txttelKeyPressed

    private void txttelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyTyped
        // TODO add your handling code here:
        char number=evt.getKeyChar();
        if(!Character.isDigit(number)){
            evt.consume();
        }
        else if(txttel.getText().length()==9){
            JOptionPane.showMessageDialog(this,"Un numéro de téléphone ne doit comporter que 9 chiffres");
        }
    }//GEN-LAST:event_txttelKeyTyped

    private void quantiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantiteKeyTyped
        // TODO add your handling code here:
        char number=evt.getKeyChar();
        if(!Character.isDigit(number)){
            evt.consume();
        }
    }//GEN-LAST:event_quantiteKeyTyped
    private void chargercdfiss(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection Conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT codefiss FROM fournisseurs";
            PreparedStatement pst=Conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            cdfiss.removeAllItems();
            while(rst.next()){
                cdfiss.addItem(rst.getString("codefiss"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erreur"+e);
        }
    }
    private void chargercmb(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT CodeMarch FROM Marchandises";
            PreparedStatement pst=conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            txtcdprod.removeAllItems();
            while(rst.next()){
                txtcdprod.addItem(rst.getString("CodeMarch"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erreur"+e);
        }
    }
    private void btnvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalActionPerformed
        // TODO add your handling code here:
        if(txtnom.getText().isEmpty()||txtpost.getText().isEmpty()||txtprn.getText().isEmpty()||txttel.getText().isEmpty()||quantite.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Zones vides non autorisées");
            txtnom.requestFocus();
        }
        else{
            try {
                String nom=txtnom.getText().toLowerCase();
                String postnom=txtpost.getText().toLowerCase();
                String prenom=txtprn.getText().toLowerCase();
                String genre=combogenr.getSelectedItem().toString();
                String tel=txttel.getText();
                String codeprod=txtcdprod.getSelectedItem().toString();
                int quant=Integer.parseInt(quantite.getText());
                String fournisseurs=cdfiss.getSelectedItem().toString();
                Class.forName("org.sqlite.JDBC");
                int fidelite=0;
                if (quant > 49) fidelite = 5;
                else if (quant > 39) fidelite = 4;
                else if (quant > 29) fidelite = 3;
                else if (quant > 19) fidelite = 2;
                else if (quant > 9) fidelite = 1;
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sqllecture="SELECT * FROM Client WHERE Tel = ?";
                PreparedStatement pst=conx.prepareStatement(sqllecture);
                pst.setString(1, tel);
                ResultSet rst=pst.executeQuery();
                if(rst.next()){
                        int nfidelite=rst.getInt("fidelite")+fidelite;
                        int nquant=rst.getInt("qtAchetee")+quant;
                        String nfiss=fournisseurs;
                        String updatefidelite="UPDATE Client SET fidelite = ?,qtAchetee = ?,cdmarch = ?,fiss = ? WHERE Tel = ? ";
                        PreparedStatement pstUpd = conx.prepareStatement(updatefidelite);
                        pstUpd.setInt(1, nfidelite);
                        pstUpd.setInt(2,nquant);
                        pstUpd.setString(3, codeprod);
                        pstUpd.setString(4, nfiss);
                        pstUpd.executeUpdate();
                        DefaultTableModel tbl = (DefaultTableModel) tb.getModel();
                        tbl.addRow(new Object[]{codeprod,nom,postnom,prenom,genre,tel,nquant,nfiss,nfidelite});
                        JOptionPane.showMessageDialog(this, "Fidélité mise à jour");
                        txtnom.setText("");
                        txtpost.setText("");
                        txtprn.setText("");
                        combogenr.setSelectedIndex(-1);
                        txttel.setText("");
                        txtcdprod.setSelectedIndex(-1);
                        quantite.setText("");
                        cdfiss.setSelectedIndex(-1);  
                }
                else{
                    String sqlEnreg="INSERT INTO Client(Tel, qtAchetee, Nom, Prenom, Postnom, Genre, fidelite, cdmarch, fiss) VALUES "+"('"+tel+"','"+quant+"','"+nom+"','"+prenom+"','"+postnom+"','"+genre+"','"+fidelite+"','"+codeprod+"','"+fournisseurs+"')";
                    PreparedStatement pstenreg=conx.prepareStatement(sqlEnreg);
                    pstenreg.executeUpdate();
                    DefaultTableModel tbl = (DefaultTableModel) tb.getModel();
                    tbl.addRow(new Object[]{codeprod,nom,postnom,prenom,genre,tel,quant,fournisseurs,fidelite});
                    JOptionPane.showMessageDialog(this, "Enregistré avec succès");
                    txtnom.setText("");
                    txtpost.setText("");
                    txtprn.setText("");
                    combogenr.setSelectedIndex(-1);
                    txttel.setText("");
                    txtcdprod.setSelectedIndex(-1);
                    quantite.setText("");
                    cdfiss.setSelectedIndex(-1);
                    
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnvalActionPerformed
    private void chargerTableau(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT * FROM Client";
            PreparedStatement pstchargerTb=conx.prepareStatement(sql);
            ResultSet rst=pstchargerTb.executeQuery();
            while(rst.next()){
                tb.removeAll();
                DefaultTableModel tab=(DefaultTableModel)tb.getModel();
                tab.addRow(new Object[]{rst.getString("cdmarch"),rst.getString("Nom"),rst.getString("Postnom"),rst.getString("Prenom"),rst.getString("Genre"),rst.getString("Tel"),rst.getInt("qtAchetee"),rst.getString("fiss"),rst.getInt("fidelite")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
        }
        
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        chargercmb();
        chargercdfiss();
        chargerTableau();
    }//GEN-LAST:event_formWindowOpened

    private void txtcdprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcdprodActionPerformed
        // TODO add your handling code here:
        quantite.requestFocus();
    }//GEN-LAST:event_txtcdprodActionPerformed

    private void btnvalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnvalKeyPressed
        // TODO add your handling code here:
        if(txtnom.getText().isEmpty()||txtpost.getText().isEmpty()||txtprn.getText().isEmpty()||combogenr.getSelectedIndex()==0||txttel.getText().isEmpty()||txtcdprod.getSelectedIndex()==0||quantite.getText().isEmpty()||cdfiss.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Zones vides non autorisées");
            txtnom.requestFocus();
        }
        else{
            try {
                String nom=txtnom.getText();
                String postnom=txtpost.getText();
                String prenom=txtprn.getText();
                String genre=combogenr.getSelectedItem().toString();
                int tel=Integer.parseInt(txttel.getText());
                String codeprod=txtcdprod.getSelectedItem().toString();
                int quant=Integer.parseInt(quantite.getText());
                String fournisseurs=cdfiss.getSelectedItem().toString();
                Class.forName("org.sqlite.JDBC");
                int fidelite=0;
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                Statement enreg=conx.createStatement();
                if(quant>10){
                    fidelite+=1;
                    Boolean L2=enreg.execute("INSERT INTO Client(Tel,Nom,Prenom,Postnom,Genre,fidelite,cdmarch,fiss)values"+"('"+tel+"','"+nom+"','"+prenom+"','"+postnom+"','"+genre+"','"+fidelite+"','"+codeprod+"','"+fournisseurs+"')");
                    if(!L2){
                        JOptionPane.showMessageDialog(this,"Enregistré avec succès");
                        DefaultTableModel tbl=(DefaultTableModel)tb.getModel();
                        tbl.addRow(new Object[]{codeprod,nom,postnom,prenom,genre,tel,quant,fournisseurs,fidelite});
                        txtnom.setText("");
                        txtpost.setText("");
                        txtprn.setText("");
                        combogenr.setSelectedIndex(0);
                        txttel.setText("");
                        txtcdprod.setSelectedIndex(0);
                        quantite.setText("");
                        cdfiss.setSelectedIndex(0);
                    }
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_btnvalKeyPressed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
        // TODO add your handling code here:
        int Row=tb.getSelectedRow();
        if(Row==-1){
            JOptionPane.showMessageDialog(this, "Veuillez selectionner une ligne à supprimer");
        }
        else{
            try {
                Class.forName("org.sqlite.JDBC");
                Connection Conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="delete from Client where Tel=?";
                PreparedStatement pst =Conx.prepareStatement(sql);
                pst.setString(1,tb.getValueAt(Row, 0).toString());
                int resultat=pst.executeUpdate();
                
               
                
                if(resultat>1){
                   JOptionPane.showMessageDialog(this,"Ligne vide");
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,"Supprimé avec succès");
                    DefaultTableModel tbident=(DefaultTableModel) tb.getModel();
                    tbident.removeRow(Row);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_btnsupprActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CAISSIER().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnret;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JButton btnval;
    private javax.swing.JComboBox<String> cdfiss;
    private javax.swing.JComboBox<String> combogenr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField quantite;
    private javax.swing.JTable tb;
    private javax.swing.JComboBox<String> txtcdprod;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtprn;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
