/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smk_supermarché;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


public class gestock extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestock.class.getName());

    /**
     * Creates new form gestock
     */
    public gestock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnval = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnret = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtidstock = new javax.swing.JTextField();
        securestock = new javax.swing.JTextField();
        quantite = new javax.swing.JTextField();
        btnEnv = new javax.swing.JButton();
        btnCommande = new javax.swing.JButton();
        cdprod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id stock", "Stock de securité", "Code Marchandise", "Quantité stockée"
            }
        ));
        jScrollPane2.setViewportView(tbl);

        jPanel5.setBackground(new java.awt.Color(102, 0, 204));

        jTextField5.setBackground(new java.awt.Color(102, 0, 204));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Ceci represente l'interface Ajout marchandises dans le stock, veuillez Selectionner votre interface");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/marchandise.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestionnaire de Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnval.setBackground(new java.awt.Color(102, 0, 204));
        btnval.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnval.setForeground(new java.awt.Color(255, 255, 255));
        btnval.setText("Stocker");
        btnval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalActionPerformed(evt);
            }
        });
        btnval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnvalKeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFIER");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SUPPR");

        btnret.setBackground(new java.awt.Color(102, 0, 204));
        btnret.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnret.setForeground(new java.awt.Color(255, 255, 255));
        btnret.setText("RETOUR");
        btnret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("IdStock:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Stock de securité:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Code Marchandise:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Quantite stockée:");

        txtidstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidstockKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidstockKeyTyped(evt);
            }
        });

        securestock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securestockKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                securestockKeyTyped(evt);
            }
        });

        quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantiteActionPerformed(evt);
            }
        });
        quantite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantiteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantiteKeyTyped(evt);
            }
        });

        btnEnv.setBackground(new java.awt.Color(102, 0, 204));
        btnEnv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnv.setForeground(new java.awt.Color(255, 255, 255));
        btnEnv.setText("SORTIR DU STOCK");
        btnEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvActionPerformed(evt);
            }
        });
        btnEnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEnvKeyPressed(evt);
            }
        });

        btnCommande.setBackground(new java.awt.Color(102, 0, 204));
        btnCommande.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCommande.setForeground(new java.awt.Color(255, 255, 255));
        btnCommande.setText("PASSER COMMANDE");
        btnCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommandeActionPerformed(evt);
            }
        });
        btnCommande.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCommandeKeyPressed(evt);
            }
        });

        cdprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cdprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnret, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quantite)
                                            .addComponent(cdprod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidstock, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(securestock))))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCommande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnval, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnret)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtidstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(securestock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cdprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnval, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5jTextField2ActionPerformed

    private void btnvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalActionPerformed
        // TODO add your handling code here:
        int securitestock=Integer.parseInt(securestock.getText());
        int qtstockee=Integer.parseInt(quantite.getText());
        if(txtidstock.getText().isEmpty()||securestock.getText().isEmpty()||quantite.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Zones vides non autorisées");
            txtidstock.requestFocus();
        }
        else if(securitestock>qtstockee){
            JOptionPane.showMessageDialog(this, "Le stock de sécurité ne doit en aucun cas être superieur à la quantité stockée"+"\n"+"veuillez entrer une valeur inférieur s'il vous plaît");
            securestock.requestFocus();
        }
        else{
            try {
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                Statement enreg=conx.createStatement();
                Boolean L2=enreg.execute("INSERT INTO stock(idstock,stock_securite,codemarch,qtstock) values"+"('"+txtidstock.getText()+"','"+securestock.getText()+"','"+cdprod.getSelectedItem().toString()+"','"+quantite.getText()+"')");
                if(!L2){
                    JOptionPane.showMessageDialog(this, "Enregistré avec succès");
                    DefaultTableModel tb=(DefaultTableModel)tbl.getModel();
                    tb.addRow(new Object[]{txtidstock.getText(),securestock.getText(),cdprod.getSelectedItem().toString(),quantite.getText()});
                    txtidstock.setText("");
                    securestock.setText("");
                    cdprod.setSelectedIndex(-1);
                    quantite.setText("");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Erreur"+e);
            }
        }
    }//GEN-LAST:event_btnvalActionPerformed

    private void btnvalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnvalKeyPressed
        // TODO add your handling code here:
        if(txtidstock.getText().isEmpty()||securestock.getText().isEmpty()||quantite.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Zones vides non autorisées");
            txtidstock.requestFocus();
        }
        else{
            
        }
    }//GEN-LAST:event_btnvalKeyPressed

    private void btnretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretActionPerformed
        // TODO add your handling code here:
        menu Menu= new menu("Gestionnaire de stock");
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnretActionPerformed

    private void txtidstockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidstockKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtidstock.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zone vides non autorisées");
            }
            else{
                securestock.requestFocus();
            }
        }
    }//GEN-LAST:event_txtidstockKeyPressed

    private void securestockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securestockKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(securestock.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                cdprod.requestFocus();
            }
        }
    }//GEN-LAST:event_securestockKeyPressed

    private void quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteActionPerformed

    private void quantiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantiteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(quantite.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zone vides non autorisées");
            }
            else{
                btnval.requestFocus();
            }
        }
    }//GEN-LAST:event_quantiteKeyPressed

    private void quantiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantiteKeyTyped
        // TODO add your handling code here:
        char number=evt.getKeyChar();
        if(!Character.isDigit(number)){
            evt.consume();
        }
    }//GEN-LAST:event_quantiteKeyTyped

    private void btnEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvActionPerformed
        // TODO add your handling code here:
        int id_stock=Integer.parseInt(JOptionPane.showInputDialog("Entrez l'id stock"));
        String codmarch=JOptionPane.showInputDialog("Entrez le code marchandise");
        int quantite_sortie=Integer.parseInt(JOptionPane.showInputDialog("Entrez la quantité à faire sortir"));
        int stocksecurite=Integer.parseInt(securestock.getText());
        int nouvelle_quantite=Integer.parseInt(quantite.getText())-quantite_sortie;
        if(nouvelle_quantite<=stocksecurite){
            JOptionPane.showMessageDialog(this, "Veuillez passer une commande avant de continuer"+"\n"+"Le stock de sécurité a été atteint");
            btnCommande.requestFocus();
        }
        else{
            try {
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="UPDATE stock set qtstock=?";
                PreparedStatement pst=conx.prepareStatement(sql);
                pst.setInt(1, id_stock);
                pst.setInt(2,stocksecurite);
                pst.setInt(3, Integer.parseInt(codmarch));
                pst.setInt(4, nouvelle_quantite);
                int lignemodifiee=pst.executeUpdate();
                
                if(lignemodifiee>=1){
                    DefaultTableModel tb=(DefaultTableModel)tbl.getModel();
                    tb.setValueAt(NORMAL, id_stock, 1);
                    tb.setValueAt(NORMAL, stocksecurite, 2);
                    tb.setValueAt(NORMAL, Integer.parseInt(codmarch),3);
                    tb.setValueAt(NORMAL, nouvelle_quantite, 4);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Modifiee avec succès");
            }
        }
        
        
    }//GEN-LAST:event_btnEnvActionPerformed

    private void btnEnvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEnvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnvKeyPressed

    private void btnCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommandeActionPerformed

    private void btnCommandeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCommandeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommandeKeyPressed

    private void txtidstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidstockKeyTyped
        // TODO add your handling code here:
        char number=evt.getKeyChar();
        if(!Character.isDigit(number)){
            evt.consume();
        }
    }//GEN-LAST:event_txtidstockKeyTyped

    private void securestockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securestockKeyTyped
        // TODO add your handling code here:
        char numb=evt.getKeyChar();
        if(!Character.isDigit(numb)){
            evt.consume();
        }
    }//GEN-LAST:event_securestockKeyTyped

    private void cdprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdprodActionPerformed
        // TODO add your handling code here:
        quantite.requestFocus();
    }//GEN-LAST:event_cdprodActionPerformed
    private void chargercdprod(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT CodeMarch FROM Marchandises ";
            PreparedStatement pst=conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            cdprod.removeAllItems();
            while(rst.next()){
                cdprod.addItem(rst.getString("CodeMarch"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        chargercdprod();
        chargertablecontent();
    }//GEN-LAST:event_formWindowOpened
    
    private void chargertablecontent(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT * FROM stock";
            PreparedStatement pst=conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            while(rst.next()){
                DefaultTableModel tb=(DefaultTableModel)tbl.getModel();
                tb.addRow(new Object[]{rst.getString("idStock"),rst.getInt("stock_securite"),rst.getString("codemarch"),rst.getInt("qtstock")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommande;
    private javax.swing.JButton btnEnv;
    private javax.swing.JButton btnret;
    private javax.swing.JButton btnval;
    private javax.swing.JComboBox<String> cdprod;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField quantite;
    private javax.swing.JTextField securestock;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtidstock;
    // End of variables declaration//GEN-END:variables
}
