/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smk_supermarché;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mengi
 */
public class logisticien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(logisticien.class.getName());
    private String role;

    /**
     * Creates new form logisticien
     */
    public logisticien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        valbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        suppr = new javax.swing.JButton();
        btnret = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcd = new javax.swing.JTextField();
        txtnomarch = new javax.swing.JTextField();
        txtnumfac = new javax.swing.JTextField();
        txtPU = new javax.swing.JTextField();
        txtPA = new javax.swing.JTextField();
        txtQt = new javax.swing.JTextField();
        cmbcatg = new javax.swing.JComboBox<>();
        cmbCdfiss = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code marchandise", "Nom marchandise", "Numero Facture", "Categorie", "Prix Unitaire", "Prix d'achat", "Quantité marchandise", "Code fournisseur", "Prix Total"
            }
        ));
        jScrollPane2.setViewportView(tb);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        valbtn.setBackground(new java.awt.Color(102, 0, 204));
        valbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valbtn.setForeground(new java.awt.Color(255, 255, 255));
        valbtn.setText("VALIDER");
        valbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valbtnActionPerformed(evt);
            }
        });
        valbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valbtnKeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFIER");

        suppr.setBackground(new java.awt.Color(255, 0, 0));
        suppr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        suppr.setForeground(new java.awt.Color(255, 255, 255));
        suppr.setText("SUPPR");
        suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprActionPerformed(evt);
            }
        });

        btnret.setBackground(new java.awt.Color(102, 0, 204));
        btnret.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnret.setForeground(new java.awt.Color(255, 255, 255));
        btnret.setText("RETOUR");
        btnret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Code Marchandise:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nom marchandise:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Numero Facture:");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Categorie:");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Prix Unitaire:");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Prix d'achat:");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Quantité marchandise:");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Code fournisseur:");

        txtcd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcdKeyTyped(evt);
            }
        });

        txtnomarch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomarchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomarchKeyTyped(evt);
            }
        });

        txtnumfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumfacActionPerformed(evt);
            }
        });
        txtnumfac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumfacKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumfacKeyTyped(evt);
            }
        });

        txtPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPUKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPUKeyTyped(evt);
            }
        });

        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        txtPA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPAKeyTyped(evt);
            }
        });

        txtQt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtActionPerformed(evt);
            }
        });
        txtQt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtKeyTyped(evt);
            }
        });

        cmbcatg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir", "Fruits", "Boissons", "Gâteau", "Chocolat" }));
        cmbcatg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcatgActionPerformed(evt);
            }
        });

        cmbCdfiss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir", "Item 2", "Item 3", "Item 4" }));
        cmbCdfiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCdfissActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnret, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQt)
                                            .addComponent(cmbCdfiss, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtcd, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtnomarch)
                                            .addComponent(txtnumfac))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtPU)
                                    .addComponent(txtPA)
                                    .addComponent(cmbcatg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnret)
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnomarch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnumfac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbcatg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtQt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbCdfiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel5.setBackground(new java.awt.Color(102, 0, 204));

        jTextField5.setBackground(new java.awt.Color(102, 0, 204));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Ceci represente l'interface Ajout marchandises, veuillez Selectionner votre interface");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/marchandise.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Logisticien");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtnumfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumfacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumfacActionPerformed

    private void btnretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretActionPerformed
        // TODO add your handling code here:
        menu Menu= new menu("Logisticien");
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnretActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtcdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtcd.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Vides non autorisés");
            }
            else{
                txtnomarch.requestFocus();
            }
        }
    }//GEN-LAST:event_txtcdKeyPressed

    private void txtnomarchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomarchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtnomarch.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Vides non autorisés");
            }
            else{
                txtnumfac.requestFocus();
            }
        }
    }//GEN-LAST:event_txtnomarchKeyPressed

    private void txtnomarchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomarchKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(Character.isDigit(numbr)){
            evt.consume();
        }
        else if(txtnomarch.getText().length()==25){
           JOptionPane.showMessageDialog(this, "Pas plus de 25 caractère pour le nom");
        }
        
    }//GEN-LAST:event_txtnomarchKeyTyped

    private void txtnumfacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumfacKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtnumfac.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Vides non autorisés");
            }
            else{
                cmbcatg.requestFocus();
            }
        }
    }//GEN-LAST:event_txtnumfacKeyPressed

    private void txtnumfacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumfacKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            evt.consume();
        }
    }//GEN-LAST:event_txtnumfacKeyTyped

    private void cmbcatgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcatgActionPerformed
        // TODO add your handling code here:
        txtPU.requestFocus();
    }//GEN-LAST:event_cmbcatgActionPerformed

    private void txtPUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPUKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtPU.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zones vide non autorisées");
            }
            else{
                txtPA.requestFocus();
            }
        }
    }//GEN-LAST:event_txtPUKeyPressed

    private void txtPUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPUKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPUKeyTyped

    private void txtPAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPAKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtPA.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Zones vide non autoriésées");
            }
            else{
                txtQt.requestFocus();
            }
        }
    }//GEN-LAST:event_txtPAKeyPressed

    private void txtPAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPAKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPAKeyTyped

    private void txtQtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtQt.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Zones vide non autorisées");
            }
            else{
                cmbCdfiss.requestFocus();
            }
        }
    }//GEN-LAST:event_txtQtKeyPressed

    private void txtQtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
           evt.consume();
        }
    }//GEN-LAST:event_txtQtKeyTyped

    private void txtcdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcdKeyTyped
        // TODO add your handling code here:
        if(txtcd.getText().length()==8){
            evt.consume();
        }
    }//GEN-LAST:event_txtcdKeyTyped

    private void valbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valbtnActionPerformed
        // TODO add your handling code here:
        if(txtcd.getText().isEmpty()||txtnomarch.getText().isEmpty()||txtnumfac.getText().isEmpty()||txtPU.getText().isEmpty()||txtPA.getText().isEmpty()||txtQt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Vides non autorisées");
        }
        else{
            try {
                String code=txtcd.getText();
                String nom_march=txtnomarch.getText();
                String facture=txtnumfac.getText();
                String catg=cmbcatg.getSelectedItem().toString();
                String fiss=cmbCdfiss.getSelectedItem().toString();
                int pu=Integer.parseInt(txtPU.getText());
                int pa=Integer.parseInt(txtPA.getText());
                int qt=Integer.parseInt(txtQt.getText());
                int qtotal=pu*qt;
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sqlread="SELECT * FROM Marchandises WHERE CodeMarch= ?";
                PreparedStatement read=conx.prepareStatement(sqlread);
                read.setString(1, code);
                ResultSet readrst=read.executeQuery();
                if(readrst.next()){
                    JOptionPane.showMessageDialog(this,"La marchandise se trouve déjà dans la base des données");
                }
                else{
                    try {
                        String sqlenreg="insert into Marchandises(CodeMarch,Nomarch,Numfac,Type,PA,Qt,Cdfiss,Pu,PrixTot) values(?,?,?,?,?,?,?,?,?)";
                        PreparedStatement enregpst=conx.prepareStatement(sqlenreg);
                        enregpst.setString(1, code);
                        enregpst.setString(2, nom_march);
                        enregpst.setString(3, facture);
                        enregpst.setString(4, catg);
                        enregpst.setInt(5, pa);
                        enregpst.setInt(6, qt);
                        enregpst.setString(7, fiss);
                        enregpst.setInt(8, pu);
                        enregpst.setInt(9, qtotal);
                        enregpst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Enregistrement fait avec succès");
                        DefaultTableModel tbl=(DefaultTableModel)tb.getModel();
                        tbl.addRow(new Object[]{code,nom_march,facture,catg,pu,pa,qt,fiss,qtotal});
                        txtcd.setText("");
                        txtnomarch.setText("");
                        txtnumfac.setText("");
                        cmbcatg.setSelectedIndex(-1);
                        txtPU.setText("");
                        txtPA.setText("");
                        txtQt.setText("");
                        cmbCdfiss.setSelectedIndex(0);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
                        e.printStackTrace();
                    }
                    conx.close();
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_valbtnActionPerformed

    private void valbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valbtnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtcd.getText().isEmpty()||txtnomarch.getText().isEmpty()||txtnumfac.getText().isEmpty()||txtPU.getText().isEmpty()||txtPA.getText().isEmpty()||txtQt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Vides non autorisées");
        }
        else{
            String code=txtcd.getText();
            String nom_march=txtnomarch.getText();
            String facture=txtnumfac.getText();
            String catg=cmbcatg.getSelectedItem().toString();
            String fiss=cmbCdfiss.getSelectedItem().toString();
            int pu=Integer.parseInt(txtPU.getText());
            int pa=Integer.parseInt(txtPA.getText());
            int qt=Integer.parseInt(txtQt.getText());
            int qtotal=pu*qt;
            try {
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sqlread="SELECT * FROM Marchandises WHERE CodeMarch= ?";
                PreparedStatement read=conx.prepareStatement(sqlread);
                read.setString(1, code);
                ResultSet readrst=read.executeQuery();
                String sqlenreg="insert into Marchandises(CodeMarch,Nomarch,Numfac,Type,PA,Qt,Cdfiss,Pu,PrixTot) values(?,?,?,?,?,?,?,?,?)";
                if(readrst.next()){
                    JOptionPane.showMessageDialog(this,"La marchandise se trouve déjà dans la base des données");
                }
                else{
                    PreparedStatement enregpst=conx.prepareStatement(sqlenreg);
                    enregpst.setString(1, code);
                    enregpst.setString(2, nom_march);
                    enregpst.setString(3, facture);
                    enregpst.setString(4, catg);
                    enregpst.setInt(5, pa);
                    enregpst.setInt(6, qt);
                    enregpst.setString(7, fiss);
                    enregpst.setInt(8, pu);
                    enregpst.setInt(9, qtotal);
                    enregpst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Enregistrement fait avec succès");
                    DefaultTableModel tbl=(DefaultTableModel)tb.getModel();
                    tbl.addRow(new Object[]{code,nom_march,facture,catg,pu,pa,qt,fiss,qtotal});
                    txtcd.setText("");
                    txtnomarch.setText("");
                    txtnumfac.setText("");
                    cmbcatg.setSelectedIndex(-1);
                    txtPU.setText("");
                    txtPA.setText("");
                    txtQt.setText("");
                    cmbCdfiss.setSelectedIndex(0);
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
        }
    }//GEN-LAST:event_valbtnKeyPressed

    private void cmbCdfissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCdfissActionPerformed
        // TODO add your handling code here:
        valbtn.requestFocus();
    }//GEN-LAST:event_cmbCdfissActionPerformed
    private void Changercmbfiss(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT Codefiss from fournisseurs";
            PreparedStatement pst=conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            cmbCdfiss.removeAllItems();
            while(rst.next()){
                cmbCdfiss.addItem(rst.getString("Codefiss"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Changercmbfiss();
        chargertbfiss();
    }//GEN-LAST:event_formWindowOpened
    private void chargertbfiss(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sqlreader="SELECT * FROM Marchandises";
            PreparedStatement pst=conx.prepareStatement(sqlreader);
            ResultSet rst=pst.executeQuery();
            while(rst.next()){
                DefaultTableModel tbident=(DefaultTableModel)tb.getModel();
                tbident.addRow(new Object[]{rst.getString("CodeMarch"),rst.getString("Nomarch"),rst.getString("Numfac"),rst.getString("Type"),rst.getInt("PU"),rst.getInt("PA"),rst.getInt("Qt"),rst.getString("Cdfiss"),rst.getString("PrixTot")} );
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e);
        }
        
    }
    private void supprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprActionPerformed
        // TODO add your handling code here:
        int Row=tb.getSelectedRow();
        if(Row==-1){
            JOptionPane.showMessageDialog(this, "Veuillez selectionner une ligne à supprimer");
        }
        else{
            try {
                Class.forName("org.sqlite.JDBC");
                Connection Conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="delete from Marchandises where CodeMarch=?";
                PreparedStatement pst =Conx.prepareStatement(sql);
                pst.setString(1,tb.getValueAt(Row, 0).toString());
                int resultat=pst.executeUpdate();
                
               
                
                if(resultat>1){
                   JOptionPane.showMessageDialog(this,"Ligne vide");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Supprimé avec succès");
                    DefaultTableModel tbident=(DefaultTableModel) tb.getModel();
                    tbident.removeRow(Row);
                }
                Conx.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_supprActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new logisticien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnret;
    private javax.swing.JComboBox<String> cmbCdfiss;
    private javax.swing.JComboBox<String> cmbcatg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton suppr;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPU;
    private javax.swing.JTextField txtQt;
    private javax.swing.JTextField txtcd;
    private javax.swing.JTextField txtnomarch;
    private javax.swing.JTextField txtnumfac;
    private javax.swing.JButton valbtn;
    // End of variables declaration//GEN-END:variables
}
