/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smk_supermarché;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mengi
 */
public class Marchandises_admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Marchandises_admin.class.getName());
    

    /**
     * Creates new form Marchandises_admin
     */
    public Marchandises_admin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cdfiss = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtprn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtpost = new javax.swing.JTextField();
        txtAd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        valbtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbfiss = new javax.swing.JTable();
        btnret = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        idstock = new javax.swing.JTextField();
        btnchercher = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbstock = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField15.setText("jTextField1");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Adresse:");

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code marchandise", "Nom ", "Postnom", "Prenom", "Genre", "Tel", "Quantite", "Code fournisseur", "Fidelite"
            }
        ));
        jScrollPane6.setViewportView(tb2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(102, 0, 204));

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/fiss.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Code fournisseur:");

        cdfiss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cdfissKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cdfissKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nom:");

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Prenom:");

        txtprn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprnActionPerformed(evt);
            }
        });
        txtprn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprnKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Post-Nom:");

        txtpost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpostKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpostKeyTyped(evt);
            }
        });

        txtAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Adresse:");

        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Tel:");

        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmailKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Mail");

        valbtn.setBackground(new java.awt.Color(0, 204, 51));
        valbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valbtn.setForeground(new java.awt.Color(255, 255, 255));
        valbtn.setText("Enregistrer");
        valbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valbtnActionPerformed(evt);
            }
        });
        valbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valbtnKeyPressed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 0, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Suppr");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cdfiss, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(valbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnmodifier))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cdfiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtprn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valbtn)
                    .addComponent(jButton6)
                    .addComponent(btnmodifier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(102, 0, 204));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Ceci represente l'interface Fournisseur, veuillez Selectionner votre interface");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        tbfiss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Fournisseur", "Nom", "Prenom", "Post-Nom", "Adresse", "Tel", "Mail"
            }
        ));
        tbfiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbfissMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbfiss);

        btnret.setBackground(new java.awt.Color(102, 0, 204));
        btnret.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnret.setForeground(new java.awt.Color(255, 255, 255));
        btnret.setText("RETOUR");
        btnret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField5)
                        .addContainerGap())
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnret, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnret)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ajout fournisseurs", jPanel5);

        jTabbedPane1.addTab("Fournisseurs", jTabbedPane3);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/acheter.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code marchandise", "Nom ", "Postnom", "Prenom", "Genre", "Tel", "Quantite", "Code fournisseur", "Fidelite"
            }
        ));
        jScrollPane2.setViewportView(tbl);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Achat");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Achat", jPanel8);

        jTabbedPane1.addTab("Achat", jTabbedPane4);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/stock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("STOCK PRODUITS");

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Id stock:");

        idstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idstockKeyPressed(evt);
            }
        });

        btnchercher.setBackground(new java.awt.Color(102, 0, 204));
        btnchercher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnchercher.setForeground(new java.awt.Color(255, 255, 255));
        btnchercher.setText("Chercher");
        btnchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idstock, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnchercher, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(idstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnchercher)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id stock", "CodeMarchandise", "Quantité stockée"
            }
        ));
        jScrollPane5.setViewportView(tbstock);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Stock_produits", jPanel11);

        jTabbedPane1.addTab("Stock", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int Row=tbfiss.getSelectedRow();
        if(Row==-1){
            JOptionPane.showMessageDialog(this, "Veuillez selectionner une ligne à supprimer");
        }
        else{
            try {
                Class.forName("org.sqlite.JDBC");
                Connection Conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="delete from fournisseurs where codefiss=?";
                PreparedStatement pst =Conx.prepareStatement(sql);
                pst.setString(1,tbfiss.getValueAt(Row, 0).toString());
                int resultat=pst.executeUpdate();
                
               
                
                if(resultat==0){
                   JOptionPane.showMessageDialog(this,"Ligne vide");
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,"Supprimé avec succès");
                    DefaultTableModel tbident=(DefaultTableModel) tbfiss.getModel();
                    tbident.removeRow(Row);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtprnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprnActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void btnretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretActionPerformed
        // TODO add your handling code here:
        menu Menu= new menu("DG");
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnretActionPerformed

    private void cdfissKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdfissKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(cdfiss.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Zone vides non autorisées");
            }
            else{
                txtnom.requestFocus();
            }
        }
    }//GEN-LAST:event_cdfissKeyPressed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtnom.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Zones vide non autorisées");
            }
            else{
                txtprn.requestFocus();
            }
        }
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtprnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtprn.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zones vide non autorisées");
            }
            else{
                txtpost.requestFocus();
            }
        }
    }//GEN-LAST:event_txtprnKeyPressed

    private void txtpostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpostKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtpost.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zones vide non autorisées");
            }
            else{
                txtAd.requestFocus();
            }
        }
    }//GEN-LAST:event_txtpostKeyPressed

    private void txtAdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtAd.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zones vide non autorisées");
            }
            else{
                txttel.requestFocus();
            }
        }
    }//GEN-LAST:event_txtAdKeyPressed

    private void txttelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txttel.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zones vide non autorisées");
            }
            else{
                txtmail.requestFocus();
            }
        }
    }//GEN-LAST:event_txttelKeyPressed

    private void txtmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(txtmail.getText().isBlank()){
                JOptionPane.showMessageDialog(this,"Zones vide non autorisées");
            }
            else{
                valbtn.requestFocus();
            }
        }
    }//GEN-LAST:event_txtmailKeyPressed

    private void cdfissKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdfissKeyTyped
        // TODO add your handling code here:
        if(cdfiss.getText().length()==8){
            JOptionPane.showMessageDialog(this,"Pas plus de 8 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_cdfissKeyTyped

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(Character.isDigit(numbr)){
            evt.consume();
        }
        else if(txtnom.getText().length()==25){
            JOptionPane.showMessageDialog(this,"Vous ne pouvez pas depacer 25 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtprnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprnKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(Character.isDigit(numbr)){
            evt.consume();
        }
        else if(txtprn.getText().length()==25){
            JOptionPane.showMessageDialog(this,"Vous ne pouvez pas depacer 25 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_txtprnKeyTyped

    private void txtpostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpostKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(Character.isDigit(numbr)){
            evt.consume();
        }
        else if(txtpost.getText().length()==25){
            JOptionPane.showMessageDialog(this,"Vous ne pouvez pas depacer 25 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_txtpostKeyTyped

    private void txtAdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(Character.isDigit(numbr)){
            evt.consume();
        }
        else if(txtAd.getText().length()==100){
            JOptionPane.showMessageDialog(this,"Vous ne pouvez pas depacer 100 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_txtAdKeyTyped

    private void txttelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyTyped
        // TODO add your handling code here:
        char numbr=evt.getKeyChar();
        if(!Character.isDigit(numbr)){
            evt.consume();
        }
        else if(txttel.getText().length()==9){
            JOptionPane.showMessageDialog(this,"Vous ne pouvez pas depacer 9 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_txttelKeyTyped

    private void txtmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyTyped
        // TODO add your handling code here:
        if(txtmail.getText().length()==100){
            JOptionPane.showMessageDialog(this,"Vous ne pouvez pas depacer 100 caractères");
            evt.consume();
        }
    }//GEN-LAST:event_txtmailKeyTyped

    private void valbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valbtnActionPerformed
        // TODO add your handling code here:
        if(cdfiss.getText().isEmpty()||txtnom.getText().isEmpty()||txtprn.getText().isEmpty()||txtpost.getText().isBlank()||txtAd.getText().isEmpty()||txttel.getText().isEmpty()||txtmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Vide non autorisées");
        }
        else{
            try {
                String fournisseur=cdfiss.getText().toLowerCase();
                String nom=txtnom.getText().toLowerCase();
                String prenom=txtprn.getText().toLowerCase();
                String post=txtpost.getText().toLowerCase();
                String Ad=txtAd.getText().toLowerCase();
                String telephone=txttel.getText();
                String mail=txtmail.getText().toLowerCase();
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="SELECT * FROM fournisseurs WHERE Nom LIKE ? AND Tel LIKE ?";
                PreparedStatement pst=conx.prepareStatement(sql);
                pst.setString(1, nom);
                pst.setString(2, telephone);
                ResultSet rst=pst.executeQuery();
                if(rst.next()){
                    JOptionPane.showMessageDialog(this, "Ces information se trouvent déjà dans la base de données veuillez modifier");
                }
                else{
                    try {
                        String sqlenreg="INSERT INTO fournisseurs(codefiss,Nom,Prenom,Postnom,Adresse,Tel,Mail) VALUES "+"('"+fournisseur+"','"+nom+"','"+prenom+"','"+post+"','"+Ad+"','"+telephone+"','"+mail+"')";
                        PreparedStatement pstenreg=conx.prepareStatement(sqlenreg);
                        int ligne=pstenreg.executeUpdate();
                        if(ligne>0){
                            JOptionPane.showMessageDialog(this, "Enregistrement réussi");
                            DefaultTableModel tbl=(DefaultTableModel)tbfiss.getModel();
                            tbl.addRow(new Object[]{fournisseur,nom,prenom,post,Ad,telephone,mail});
                            cdfiss.setText("");
                            txtnom.setText("");
                            txtprn.setText("");
                            txtpost.setText("");
                            txtAd.setText("");
                            txttel.setText("");
                            txtmail.setText("");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Enregistrement échoué");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
                    }
                }
                conx.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
            
        }
    }//GEN-LAST:event_valbtnActionPerformed

    private void valbtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valbtnKeyPressed
        // TODO add your handling code here:
        if(cdfiss.getText().isEmpty()||txtnom.getText().isEmpty()||txtprn.getText().isEmpty()||txtpost.getText().isBlank()||txtAd.getText().isEmpty()||txttel.getText().isEmpty()||txtmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Vide non autorisées");
        }
        else{
            try {
                String fournisseur=cdfiss.getText().toLowerCase();
                String nom=txtnom.getText().toLowerCase();
                String prenom=txtprn.getText().toLowerCase();
                String post=txtpost.getText().toLowerCase();
                String Ad=txtAd.getText().toLowerCase();
                String telephone=txttel.getText();
                String mail=txtmail.getText().toLowerCase();
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="SELECT * FROM fournisseurs WHERE Nom LIKE ? AND Tel LIKE ?";
                PreparedStatement pst=conx.prepareStatement(sql);
                pst.setString(1, nom);
                pst.setString(2, telephone);
                ResultSet rst=pst.executeQuery();
                if(rst.next()){
                    JOptionPane.showMessageDialog(this, "Ces information se trouvent déjà dans la base de données veuillez modifier");
                }
                else{
                    try {
                        String sqlenreg="INSERT INTO fournisseurs(codefiss,Nom,Prenom,Postnom,Adresse,Tel,Mail) VALUES "+"('"+fournisseur+"','"+nom+"','"+prenom+"','"+post+"','"+Ad+"','"+telephone+"','"+mail+"')";
                        PreparedStatement pstenreg=conx.prepareStatement(sqlenreg);
                        int ligne=pstenreg.executeUpdate();
                        if(ligne>0){
                            JOptionPane.showMessageDialog(this, "Enregistrement réussi");
                            DefaultTableModel tbl=(DefaultTableModel)tbfiss.getModel();
                            tbl.addRow(new Object[]{fournisseur,nom,prenom,post,Ad,telephone,mail});
                            cdfiss.setText("");
                            txtnom.setText("");
                            txtprn.setText("");
                            txtpost.setText("");
                            txtAd.setText("");
                            txttel.setText("");
                            txtmail.setText("");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Enregistrement échoué");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
            
        }
    }//GEN-LAST:event_valbtnKeyPressed
    private void chargertableContents(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection Conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT * FROM Client ";
            PreparedStatement pst=Conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            while(rst.next()){
                DefaultTableModel tb=(DefaultTableModel)tbl.getModel();
                tb.addRow(new Object[]{
                    rst.getString("cdmarch"),
                    rst.getString("Nom"),
                    rst.getString("Postnom"),
                    rst.getString("Prenom"),
                    rst.getString("Genre"),
                    rst.getString("Tel"),
                    rst.getString("qtAchetee"),
                    rst.getString("fiss"),
                    rst.getString("fidelite")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
        }
    }
    private void chargerTableFiss(){
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
            String sql="SELECT * FROM fournisseurs";
            PreparedStatement pst=conx.prepareStatement(sql);
            ResultSet rst=pst.executeQuery();
            while(rst.next()){
                DefaultTableModel tb=(DefaultTableModel)tbfiss.getModel();
                tb.addRow(new Object[]{rst.getString("codefiss"),  rst.getString("Nom"),rst.getString("Prenom"),rst.getString("Postnom"),rst.getString("Adresse"),rst.getString("Tel"),rst.getString("Mail")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        chargertableContents();
        chargerTableFiss();
    }//GEN-LAST:event_formWindowOpened

    private void btnchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchercherActionPerformed
        // TODO add your handling code here:
        if(idstock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez remplir la zone de texte svp!");
            idstock.requestFocus();
        }
        else{
            try {
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="SELECT * FROM stock WHERE idStock = ?";
                PreparedStatement pst=conx.prepareStatement(sql);
                pst.setString(1, idstock.getText());
                ResultSet rst=pst.executeQuery();
                DefaultTableModel tb=(DefaultTableModel)tbstock.getModel();
                int i;
                boolean existedeja=false;
                for(i=0;i<tb.getRowCount(); i++){
                    if(tb.getValueAt(i,0).equals(rst.getString("idstock"))){
                        existedeja=true;
                    }
                }
                if(rst.next()){
                    if(!existedeja){
                        tb.addRow(new Object[]{rst.getString("idStock"),rst.getString("codemarch"),rst.getString("qtstock")});
                        JOptionPane.showMessageDialog(this, "Trouvé");
                        idstock.setText("");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Cet élement est déjà dans la base de données");
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Cet élement n'est pas dans la base de données");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnchercherActionPerformed

    private void idstockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idstockKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            if(idstock.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Veuillez remplir la zone vide");
            }
            else{
                btnchercher.requestFocus();
            }
        }
    }//GEN-LAST:event_idstockKeyPressed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
        int row=tbfiss.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Veuillez selectionner une ligne afin de modifier");
        }
        else{
            try {
                String cd=cdfiss.getText();
                String nom=txtnom.getText();
                String prenom=txtprn.getText();
                String postnom=txtpost.getText();
                String Adresse=txtAd.getText();
                String tel=txttel.getText();
                String mail=txtmail.getText();
                Class.forName("org.sqlite.JDBC");
                Connection conx=DriverManager.getConnection("jdbc:sqlite:C:\\Users\\mengi\\Documents\\SMK_SuperMarché\\SMKApp.db");
                String sql="UPDATE fournisseurs SET Nom=?, Prenom=?, Postnom=?,Adresse=?,Tel=?,Mail=? WHERE codefiss=?";
                PreparedStatement pst=conx.prepareStatement(sql);
                pst.setString(1, nom);
                pst.setString(2,prenom);
                pst.setString(3,postnom);
                pst.setString(4, Adresse);
                pst.setString(5, tel);
                pst.setString(6,mail);
                pst.setString(7, cd);
                int resultat=pst.executeUpdate();
                if(resultat>0){
                    JOptionPane.showMessageDialog(this,"Modification effectuée avec succès");
                    tbfiss.setValueAt(cd, row, 0);
                    tbfiss.setValueAt(nom, row, 1);
                    tbfiss.setValueAt(prenom, row, 2);
                    tbfiss.setValueAt(postnom, row, 3);
                    tbfiss.setValueAt(Adresse, row, 4);
                    tbfiss.setValueAt(tel, row, 5);
                    tbfiss.setValueAt(mail, row, 6);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Aucune ligne trouvée");
                }
                conx.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur"+e);
            }
        }
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void tbfissMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbfissMouseClicked
        // TODO add your handling code here:
        int row=tbfiss.getSelectedRow();
        if(row!=-1){
            cdfiss.setText(tbfiss.getValueAt(row, 0).toString());
            txtnom.setText(tbfiss.getValueAt(row, 1).toString());
            txtprn.setText(tbfiss.getValueAt(row, 2).toString());
            txtpost.setText(tbfiss.getValueAt(row, 3).toString());
            txtAd.setText(tbfiss.getValueAt(row, 4).toString());
            txttel.setText(tbfiss.getValueAt(row, 5).toString());
            txtmail.setText(tbfiss.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_tbfissMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Marchandises_admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchercher;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnret;
    private javax.swing.JTextField cdfiss;
    private javax.swing.JTextField idstock;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tbfiss;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbstock;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtprn;
    private javax.swing.JTextField txttel;
    private javax.swing.JButton valbtn;
    // End of variables declaration//GEN-END:variables
}
